server:
  port: 8764
  
spring:
  application: 
    name: customer
   
eureka:
  instance:
    appname: customer
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
feign:  
  hystrix:  
    enabled: true 
    
foo:
  demo bus testxxx 